module.exports = [
  {
    title: "Git",
    icon: "git",
    collapsable: false,
    children: [
      "",
      "install",
      "intro",
      "create-repo",
      "status",
      "recall",
      "reset",
      "working-directory",
      "change",
      "remote",
      "branch",
      "tag",
      "ignore",
      "working",
      "custom",
    ],
  },
  {
    title: "Github",
    icon: "Github",
    collapsable: false,
    prefix: "github/",
    children: ["", "intro", "pr", "semantic", "actions", "deploy"],
  },
];
