module.exports = [
  "",
  "editor",
  {
    title: "VS Code",
    icon: "vscode",
    collapsable: false,
    prefix: "vscode/",
    children: require("./vscode"),
  },
  "Chrome",
  {
    title: "Git",
    icon: "git",
    collapsable: false,
    prefix: "git/",
    children: require("./git"),
  },
  {
    title: "Github",
    icon: "Github",
    collapsable: false,
    prefix: "git/github/",
    children: ["", "intro", "pr", "semantic", "actions", "deploy"],
  },
  {
    title: "COMSOL",
    icon: "app",
    collapsable: false,
    prefix: "comsol/",
    children: require("./comsol"),
  },
  {
    title: "工具软件",
    icon: "tool",
    collapsable: false,
    prefix: "tool/",
    children: ["", "power-toys"],
  },
  "Apache",
  "nginx",
];
