allowBuilds:
  "@parcel/watcher": true
  esbuild: true

configDependencies:
  pacquet: "^0.11.10"

enableGlobalVirtualStore: true

packageExtensions:
  # FIXME: This is a bug in mathjax
  "@mathjax/mathjax-newcm-font":
    peerDependencies:
      "@mathjax/src": ^4.1.2

  # FIXME: This is a bug in mathjax
  "@mathjax/mathjax-tex-font":
    peerDependencies:
      "@mathjax/src": ^4.1.2
