allowBuilds:
  "@parcel/watcher": true
  esbuild: true

enableGlobalVirtualStore: true

minimumReleaseAgeExclude:
  - "@vuepress/*"
  - vuepress-plugin-components
  - vuepress-plugin-md-enhance
  - vuepress-shared
  - vuepress-theme-hope

packageExtensions:
  # FIXME: This is a bug in mathjax
  "@mathjax/mathjax-newcm-font":
    peerDependencies:
      "@mathjax/src": ^4.1.2

  # FIXME: This is a bug in mathjax
  "@mathjax/mathjax-tex-font":
    peerDependencies:
      "@mathjax/src": ^4.1.2
