import type { HopeThemeSidebarArrayConfig } from "vuepress-theme-hope";

export const guide: HopeThemeSidebarArrayConfig = [
  "README.md",
  "file-structure.md",
  "env.md",
  {
    text: "配置",
    icon: "config",
    prefix: "config/",
    children: [
      "README.md",
      "app-config.md",
      "page-config.md",
      "sitemap-config.md",
    ],
  },
  {
    text: "框架",
    icon: "frame",
    prefix: "frame/",
    children: ["intro.md", "scene.md", "env.md", "mechanism.md", "update.md"],
  },
  {
    text: "逻辑层",
    icon: "process",
    prefix: "service/",
    children: [
      "README.md",
      "lifetime.md",
      "route.md",
      "register.md",
      "app.md",
      "page.md",
      "run.md",
      "module.md",
      {
        text: "API",
        icon: "api",
        prefix: "api/",
        children: [
          "README.md",
          "route.md",
          "storage.md",
          "interact.md",
          "network.md",
          "system.md",
        ],
      },
    ],
  },
  {
    text: "视图层",
    icon: "layout",
    prefix: "view/",
    children: [
      "README.md",
      {
        text: "WXML",
        icon: "code",
        collapsable: true,
        children: [
          "wxml.md",
          "data-bind.md",
          "condition-render.md",
          "list-render.md",
          "template.md",
        ],
      },
      "wxss.md",
      "event.md",
      "component.md",
      "animation.md",
      "wxs.md",
      "wxs-event.md",
      "model.md",
      "selector.md",
      "rendering-cache.md",
    ],
  },
  {
    text: "能力",
    icon: "safe",
    prefix: "ability/",
    children: [
      "README.md",
      "network.md",
      "storage.md",
      "file-system.md",
      "debug.md",
    ],
  },
];
