module.exports = [
  "",
  {
    title: "快速上手",
    icon: "creative",
    collapsable: false,
    prefix: "guide/",
    children: [
      "",
      "selector",
      "declaration",
      "import",
      "cascade",
      "box",
      "common",
    ],
  },
  "box",
  "selector",
  "background-and-border",
  "text-direction",
  "overflow",
  {
    title: "CSS 布局",
    icon: "layout",
    collapsable: false,
    prefix: "layout/",
    children: ["", "flex", "exercise", "grid"],
  },
  "media",
];
