module.exports = [
  "",
  "fileStructure",
  "env",
  "config/",
  "frame",
  {
    title: "逻辑层",
    icon: "process",
    collapsable: false,
    prefix: "service/",
    children: [
      "",
      "lifetime",
      "route",
      "register",
      "app",
      "page",
      "run",
      "module",
      {
        title: "API",
        icon: "api",
        prefix: "api/",
        children: ["", "route", "storage", "interact", "network", "system"],
      },
    ],
  },
  {
    title: "视图层",
    icon: "layout",
    collapsable: false,
    prefix: "view/",
    children: [
      "",
      {
        title: "WXML",
        icon: "code",
        children: [
          "wxml",
          "databind",
          "conditionrender",
          "listrender",
          "template",
        ],
      },
      "wxss",
      "wxs",
      "event",
      "component",
      "animation",
    ],
  },
  {
    title: "能力",
    icon: "safe",
    collapsable: false,
    prefix: "ability/",
    children: ["", "network", "storage", "fileSystem", "debug"],
  },
];
