module.exports = [
  "",
  {
    title: "图标",
    icon: "discover",
    collapsable: false,
    prefix: "icon/",
    children: [
      "",
      "intro",
      "guide",
      "software",
      "line",
      "line-exercise",
      "flour",
      "decorative",
      "start",
      "skill",
      "apply",
    ],
  },
  {
    title: "导航",
    icon: "navigate",
    collapsable: false,
    prefix: "navigation/",
    children: ["explain", "navbar-design", "sidebar-navigate"],
  },
  "search",
  "APP",
];
