import type { HopeThemeSidebarArrayConfig } from "vuepress-theme-hope";

export const linux: HopeThemeSidebarArrayConfig = [
  "README.md",
  {
    text: "简介",
    icon: "info",
    link: "intro/",
    prefix: "intro/",
    children: [
      "intro.md",
      "history.md",
      "language.md",
      "advantage.md",
      "desktop.md",
    ],
  },
  {
    text: "文件结构",
    icon: "file",
    link: "file/",
    prefix: "file/",
    children: ["file.md", "dir.md", "mount.md"],
  },
  {
    text: "命令",
    icon: "program",
    link: "command/",
    prefix: "command/",
    children: [
      "command.md",
      "dir.md",
      "file.md",
      "other.md",
      "add.md",
      "excu.md",
      "path.md",
      "ln.md",
    ],
  },
  {
    text: "Bash",
    icon: "program",
    link: "bash/",
    prefix: "bash/",
    children: [
      "intro.md",
      "grammar.md",
      "expansion.md",
      "quotation.md",
      "variable.md",
      "string.md",
      "arithmetic.md",
      "readline.md",
      "stack.md",
      "script.md",
      "read.md",
      "condition.md",
      "loop.md",
      "function.md",
      "array.md",
      "set.md",
      "debug.md",
      "mktemp.md",
      "startup.md",
      "prompt.md",
    ],
  },
  {
    text: "ubuntu",
    icon: "ubuntu",
    link: "ubuntu/",
    prefix: "ubuntu/",
    children: ["manage.md", "debug.md", "webserver.md", "lang.md"],
  },
  "centos.md",
  "WSL.md",
  "ssh.md",
];
