const { sidebarConfig } = require("vuepress-theme-hope");

module.exports = sidebarConfig([
  "",
  {
    title: "简介",
    icon: "info",
    path: "intro/",
    collapsable: false,
    prefix: "intro/",
    children: ["intro", "history", "language", "advantage", "desktop"],
  },
  {
    title: "文件结构",
    icon: "file",
    path: "file/",
    collapsable: false,
    prefix: "file/",
    children: ["file", "dir", "mount"],
  },
  {
    title: "命令",
    icon: "program",
    path: "command/",
    prefix: "command/",
    collapsable: false,
    children: ["command", "dir", "file", "other", "add", "excu", "path", "ln"],
  },
  {
    title: "Bash",
    icon: "program",
    path: "bash/",
    prefix: "bash/",
    collapsable: false,
    children: [
      "intro",
      "grammar",
      "expansion",
      "quotation",
      "variable",
      "string",
      "arithmetic",
      "readline",
      "stack",
      "script",
      "read",
      "condition",
      "loop",
      "function",
      "array",
      "set",
      "debug",
      "mktemp",
      "startup",
      "prompt",
    ],
  },
  {
    title: "ubuntu",
    icon: "ubuntu",
    path: "ubuntu/",
    prefix: "ubuntu/",
    collapsable: false,
    children: ["manage", "debug", "webserver", "lang"],
  },
  "centos",
  "WSL",
  "ssh",
]);
