import type { HopeThemeSidebarArrayConfig } from "vuepress-theme-hope";

export const note: HopeThemeSidebarArrayConfig = [
  "README.md",
  {
    text: "秋之思",
    icon: "autumn",
    prefix: "fall/",
    children: [
      "README.md",
      "catalog.md",
      "1.md",
      "2.md",
      "3.md",
      "4.md",
      "5.md",
      "6.md",
      "7.md",
      "8.md",
      "9.md",
      "10.md",
      "11.md",
      "12.md",
      "13.md",
      "14.md",
      "15.md",
      "16.md",
      "special.md",
      "moon1.md",
      "moon2.md",
      "17.md",
      "end.md",
      "18.md",
      "19.md",
      "20.md",
      "21.md",
      "22.md",
      "23.md",
      "24.md",
      "25.md",
      "miss1.md",
      "miss2.md",
      "26.md",
      "middle-autumn.md",
    ],
  },
  {
    text: "冬之语",
    icon: "snow",
    prefix: "winter/",
    children: [
      "README.md",
      "note.md",
      "1.md",
      "2.md",
      "3.md",
      "4.md",
      "5.md",
      "6.md",
      "7.md",
      "8.md",
      "newyear.md",
      "9.md",
      "10.md",
      "11.md",
      "12.md",
      "newyear2.md",
    ],
  },
  {
    text: "春之诗",
    icon: "flower",
    prefix: "spring/",
    children: ["README.md", "catalog.md", "1.md", "2.md", "3.md"],
  },
  {
    text: "夏之歌",
    icon: "leaf",
    prefix: "summer/",
    children: ["README.md", "1.md", "2.md", "3.md"],
  },
  {
    text: "笑谈人生",
    icon: "form",
    prefix: "life/",
    children: [
      "README.md",
      "1.md",
      "2.md",
      "3.md",
      "4.md",
      "5.md",
      "6.md",
      "7.md",
      "8.md",
      "9.md",
      "step.md",
      "pure.md",
      "year.md",
      "life.md",
      "emotion.md",
      "friendship.md",
      "family.md",
      "love.md",
      "indifferent.md",
      "road.md",
      "choice.md",
      "calm.md",
      "birthday.md",
    ],
  },
  {
    text: "轻言细语",
    icon: "like",
    prefix: "poem/",
    children: [
      "README.md",
      "1.md",
      "2.md",
      "3.md",
      "4.md",
      "5.md",
      "6.md",
      "7.md",
      "8.md",
      "9.md",
      "10.md",
      "11.md",
      "exam.md",
      "sad.md",
      "12.md",
      "13.md",
      "11-11.md",
      "14.md",
    ],
  },
  "node-js/README.md",
];
