module.exports = [
  "",
  {
    title: "HTML",
    icon: "html",
    collapsable: false,
    prefix: "html/",
    children: [
      "",
      "get-started",
      "head",
      "basic",
      "link",
      "emmet",
      "format",
      "layout",
    ],
  },
  {
    title: "CSS",
    icon: "css",
    collapsable: false,
    prefix: "css/",
    children: ["", "intro", "detail", "layout"],
  },
  "js",
  {
    title: "jQuery",
    icon: "jQuery",
    collapsable: false,
    path: "jQuery/",
    prefix: "jQuery/",
    children: [
      "",
      "intro",
      "selector",
      "operateDOM",
      "modifyDOM",
      "event",
      "animation",
      "AJAX",
      "extend",
    ],
  },
  "https",
];
